'''
This file contains the configuration of the hardware used in the lab.
Contains all the information potentially needed in the user experiment code file.
'''
# TODO --> this config could be updated autamtically ? (hard to do... but partially feasible)
# Remove things will be never be called in the code of the experiment ?
# Tackle the different formats for expyriments / matlab / psychoPy / etc. ?

#------------- REQUIRED --------------#
meg_system: "Elekta Neuromag"
  meg_pc: "Dell Precision 7920"
  meg_software: "Elekta Neuromag"
  meg_software_version: "4.0.0"
  digitalization: "ADC-16"

eeg_system: "BrainProducts ActiChamp" 
  eeg_pc: "Dell Precision 7920"
  eeg_software: "BrainVision Recorder"
  eeg_software_version: "1.23.0001"

stimulus_pc: "Dell Precision 7920"
  x_shift: -300
  luminosity: 100

projector: "Epson EB-2255U"
  resolution: [1920, 1200]
  refresh_rate: 60
  screen_size: 100

parallel_ports: 
  port1: "/dev/parport0"
  port2: "/dev/parport1"
  port3: "/dev/parport2"
  port4: "/dev/parport3" 
#TODO definir les correspondances (et en hexadécimal aussi "0x0378"?)


#------------- OPTIONAL --------------#
photodiode: ""
  channel: "MISC006"

response_button:
  buttons: ["STI012", "STI013", "STI014", "STI015"]
  labels: ["red", "yellow", "green", "red"]

audio_system:
  speakers: "Logitech Z906"
  headphones: "Sennheiser HD 650"
  channels: ["MISC004", "MISC005"]

eyelink_system:
  eyelink_pc: "Dell Precision 7920"
  eyelink_software: "SR Research Experiment Builder"
  eyelink_software_version: "2.0.0"
  calibration: "9 points"
  sampling_rate: 1000
  drift_correction: True