# This file contains the configuration of the hardware used in the lab.
# Contains all the information potentially needed in the user experiment code file.
# TODO --> this config could be updated automatically? (hard to do... but partially feasible)
stim_pc:
  name: "Dell Precision 7920"
  parport: 
    port1: "/dev/parport0"
    port2: "/dev/parport1"
    port3: "/dev/parport2"


response_buttons:
  used_ports: 
    - "/dev/parport0"
    - "/dev/parport1"
  buttons:
    l_red: "STI012"
    l_yellow: "STI013"
    l_green: "STI014"
    l_blue: "STI015"
    r_red: "STI012"
    r_yellow: "STI013"
    r_green: "STI014"
    r_blue: "STI015"


eyelink_system:
  eyelink_pc: "Dell Precision 7920"
  eyelink_software: "SR Research Experiment Builder"
  eyelink_software_version: "2.0.0"
  calibration: "9 points"
  sampling_rate: 1000
  drift_correction: true


projector: 
  name: "Epson EB-2255U"
  refresh_rate: 120
  x_shift: -300


photodiode:
  ttl: 
    - "MISC006"

audio_system:
  name: ~
  speakers: "Logitech Z906"
  headphones: "Sennheiser HD 650"
  ttl: 
    - "MISC004"
    - "MISC005"



meg_system: null  # Si non utilisé, mettre `null` plutôt que commenter tout le bloc
#   meg_pc: "Dell Precision 7920"
#   meg_software: "Elekta Neuromag"
#   meg_software_version: "4.0.0"
#   digitalization: "ADC-16"

eeg_system: null
#   eeg_pc: "Dell Precision 7920"
#   eeg_software: "BrainVision Recorder"
#   eeg_software_version: "1.23.0001"
